name: Metrics

on:
  schedule:
    - cron: "0 21 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: devsamuelmwangi

          filename: github-metrics.svg
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Africa/Nairobi
          config_twemoji: yes
          config_display: large

          plugin_languages: yes
          plugin_languages_sections: most-used

          plugin_languages_categories: programming, markup, data
          plugin_languages_limit: 12
          plugin_languages_details: percentage, bytes-size
          plugin_languages_ignored: html, css

          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 30

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_stars: yes
          plugin_followup: yes

          plugin_pagespeed: yes
          plugin_pagespeed_url: https://devsamuelmwangi.web.app
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}

          plugin_topics: yes
          plugin_topics_mode: mastered
          plugin_topics_limit: 12
